### ISSUE TITLE
Inizializzazione Vue guest.welcome

### ISSUE THREAD

**Issue by GiovanniConti** [LeonardoCeccarelli/boolbnb#11]
Inizializzazione Vue lato guest.

**Comment by LeonardoCeccarelli** [comment]
Hero section con un button che ci porta all'index senza nessun filtro e un button che ci porta sempre all'index ma come filtri i campi città e posti letto

mostrare i primi 10 appartamenti in evidenza

mostrare crad con città più importanti dove al click ci rimanda all'index con il filtro della città che equivale alla card della città cliccata
